name: circular_pattern
description: An alternative data input widget for flutter, consisting of circular dots.
version: 0.1.1
homepage: https://github.com/agtrlabs/circular_pattern.git

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
