name: circular_pattern
description: Circular Pattern is a flutter widget that works similar to pattern lock whick pattern dots are in a circular form.
version: 0.0.1
homepage: https://gitlab.com/turkiye/agtr/circular_pattern

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
